### ISSUE TITLE
CDU Incorreto na ficha catalográfica

### ISSUE THREAD

**Issue by danielsaad** [IFBmodels/tcc#2]
O CDU 002 está incorreto, ele é destinado para a área de biblioteconomia.
Geralmente o CDU da Informática começa com prefixo 004.

Para referência: https://pt.wikipedia.org/wiki/Classifica%C3%A7%C3%A3o_decimal_universal

**Comment by auyer** [comment]
Issue transferida para novo repositório, e resolvida.
